from typing import Any, Protocol

class NodeEnvironment(Protocol):
    @property
    def engine(self) -> Any: ...
    @property
    def writer(self) -> Any: ...
    @property
    def config(self) -> dict[str, Any]: ...

class BaseNode(Protocol):
    def __init__(self, node_def: dict[str, Any], env: NodeEnvironment) -> None: ...
    
    def execute(self, state: Any) -> Any: ...
